"""initial_schema

Revision ID: 184c30feba59
Revises: 
Create Date: 2026-02-28 17:02:28.934625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184c30feba59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('total_calculations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('calculation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('calculation_type', sa.String(length=20), nullable=False),
    sa.Column('gross_annual', sa.Float(), nullable=False),
    sa.Column('chargeable_income', sa.Float(), nullable=False),
    sa.Column('annual_tax', sa.Float(), nullable=False),
    sa.Column('effective_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
